name: Deploy API

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: npm install
      
    - name: Build
      run: npm run build
      
    - name: Deploy to Digital Ocean
      env:
        DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
        SPACES_ACCESS_KEY: ${{ secrets.SPACES_ACCESS_KEY }}
        SPACES_SECRET_KEY: ${{ secrets.SPACES_SECRET_KEY }}
        SSH_KEY_FINGERPRINT: ${{ secrets.SSH_KEY_FINGERPRINT }}
        DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      run: |
        # Install doctl
        wget https://github.com/digitalocean/doctl/releases/download/v1.92.0/doctl-1.92.0-linux-amd64.tar.gz
        tar xf doctl-1.92.0-linux-amd64.tar.gz
        sudo mv doctl /usr/local/bin
        
        # Auth with DO
        doctl auth init -t $DO_API_TOKEN
        
        # Setup SSH
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts
        
        # Deploy
        rsync -avz --delete ./dist/ root@$DEPLOY_HOST:/root/deiex-api/
        ssh root@$DEPLOY_HOST 'cd /root/deiex-api && pm2 restart deiex-api'
